-----------------------------------------------------------------------------
--------------------------------CORRECIONES----------------------------------
-----------------------------------------------------------------------------

CREATE TABLE actor.PERSONA_FISICA(
	ID INT2 NOT NULL,
	ID_ACTOR INT2 NOT NULL,
	ID_OCUPACION INT2 NULL,
	DOCUMENTO_IDENTIDAD_TIPO VARCHAR(1) NOT NULL,
	DOCUMENTO_IDENTIDAD_NUMERO INT4 NOT NULL,
	APELLIDO VARCHAR(255) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	NOMBRE VARCHAR(255) NOT NULL,
	MOVIL_PRINCIPAL VARCHAR(255) NULL,
	SEXO CHAR(1) NOT NULL,
	APELLIDO_MATERNO VARCHAR(255) NULL,
	FACTOR_SANGUINEO VARCHAR(255) NULL,
	GRUPO_SANGUINEO VARCHAR(255) NULL,
	DONANTE_ORGANOS VARCHAR(255) NULL,
	EMAIL_PERSONAL VARCHAR(255) NULL,
	ESTADO_CIVIL CHAR(1) NOT NULL,
	CONSTRAINT pk_persona_fisica PRIMARY KEY(ID),	
	CONSTRAINT uk_persona_fisica_1 UNIQUE(ID_ACTOR),
	CONSTRAINT uk_persona_fisica_2 UNIQUE(DOCUMENTO_IDENTIDAD_TIPO, DOCUMENTO_IDENTIDAD_NUMERO),
	CONSTRAINT fk_persona_fisica_actor FOREIGN KEY(ID_ACTOR)
		REFERENCES actor.ACTOR(ID),
	CONSTRAINT fk_persona_fisica_ocupacion FOREIGN KEY(ID_OCUPACION)
		REFERENCES actor.OCUPACION(ID),
	CONSTRAINT check_persona_fisica
	CHECK (ESTADO_CIVIL IN ('S', 'C', 'E', 'D', 'V', 'N'))
);